### ISSUE TITLE
A bug need to fix.

### ISSUE THREAD

**Issue by wersdfxcvlwy** [ItsVixano-releases/LineageOS_sakura#1]
I'm so sorry that my English is poor.I found this rom and I loved this rom when I was first use it.It is a great rom.But I find a bug.When I open a app.And I use gusture to "recent apps"  then I tap this app's icon.But it didn't give me a menu always.Please fix this bug if you are free.So thanks!

**Comment by ItsVixano** [comment]
Hi, are you sure you are running the latest version ??

**Comment by wersdfxcvlwy** [comment]
![_-695261102__d0666f2f1ecbd41d38e96ad20e26f885_1790387441_Screenshot_20230802-195416_设置_0_wifi_0](https://github.com/ItsVixano-releases/LineageOS_sakura/assets/124040716/8178f1f7-0cde-4a47-9ac2-409d6a7d90a5)
Sure.

**Comment by ItsVixano** [comment]
Ok yeah, i managed to replicate it on my unit, i'll find a way to fix it :+1:

**Comment by wersdfxcvlwy** [comment]
So thanks.😋

**Comment by ItsVixano** [comment]
Mind rechecking it again on today update ?
